### ISSUE TITLE
Uncaught TypeError: Cannot read property 'update' of null

### ISSUE THREAD

**Issue by Octowl** [artoale/atom-tern#16]
Uncaught TypeError: Cannot read property 'update' of null

**Atom Version**: 0.161.0
**System**: Mac OS X 10.10.1
**Thrown From**: [Tern](https://github.com/artoale/atom-tern) package, v0.8.0
### Steps To Reproduce
1. type a '.'
2. hit cmd-space
### Stack Trace

```
At /Users/aziz/.atom/packages/Tern/lib/tern.coffee:9

TypeError: Cannot read property 'update' of null
  at Object.module.exports.update (/Users/aziz/.atom/packages/Tern/lib/tern.coffee:9:15)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/node_modules/underscore/underscore.js:701:23
  at TextBuffer.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1143:17

```

/cc @atom/core

**Comment by Octowl** [comment]
This error stopped as soon as I started the tern server

It's still kind of annoying that it will appear unless I manually start the server.

**Comment by edoloughlin** [comment]
This doesn't stop for me when the tern server is running. I have to disable the tern package.

**Comment by patrickse** [comment]
Facing the same problem... I just receive this message and I am not able to use atom-tern.

**Comment by murdockcrc** [comment]
same here
