### ISSUE TITLE
Failed to activate the Tern package

### ISSUE THREAD

**Issue by anildigital** [artoale/atom-tern#19]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [Tern](https://github.com/artoale/atom-tern) package, v0.8.0
### Stack Trace

Failed to activate the Tern package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/anil/.atom/packages/Tern/lib/tern-view.coffee:1:1)
  at /Users/anil/.atom/packages/Tern/lib/tern-view.coffee:6:5
  at Object.<anonymous> (/Users/anil/.atom/packages/Tern/lib/tern-view.coffee:129:5)
  at Object.<anonymous> (/Users/anil/.atom/packages/Tern/lib/tern-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/anil/.atom/packages/Tern/lib/tern.coffee:1:12)
  at Object.<anonymous> (/Users/anil/.atom/packages/Tern/lib/tern.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:257:12)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:236:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:772:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:219:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-li.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
  at HTMLOListElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLOListElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
     -0:11 editor:newline (atom-text-editor.editor.is-focused)
  4x -0:07.3.0 core:undo (atom-text-editor.editor.is-focused)
     -0:04.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.3.0 tern:start-server (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "useReactEditor": true,
    "themes": [
      "spacegray-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Tern, v0.8.0
color-picker, v2.0.4
editor-stats, vundefined
file-icons, v1.5.7
keyboard-sounds, v0.2.0
linter, v0.12.7
linter-jshint, v0.1.6
linter-rubocop, v0.2.7
minimap, v4.10.0
pretty-json, v0.3.3
project-manager, v1.15.10
react, v0.12.0
spacegray-dark-ui, v0.12.0

# Dev
No dev packages
```

**Comment by jpsmith1981** [comment]
I am also experiencing this issue

**Comment by shd101wyy** [comment]
same here

**Comment by robin-barnes-triptease** [comment]
I'm getting this too

**Comment by lxmarduk** [comment]
same on tern server start
