### ISSUE TITLE
Failed to load the Tern package

### ISSUE THREAD

**Issue by raghavkaul** [artoale/atom-tern#27]
Tern crashes upon atom reload after "apm install tern". 

**Atom Version**: 1.1.0
**System**: "Arch Linux"
**Thrown From**: [Tern](https://github.com/artoale/atom-tern) package, v0.8.0
### Stack Trace

Failed to load the Tern package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/home/user1316/.atom/packages/Tern/lib/tern-view.coffee:1:1)
    at /home/user1316/.atom/packages/Tern/lib/tern-view.coffee:6:5
    at Object.<anonymous> (/home/user1316/.atom/packages/Tern/lib/tern-view.coffee:6:5)
    at Object.<anonymous> (/home/user1316/.atom/packages/Tern/lib/tern-view.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "projectHome": "~/CODE",
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```
### Installed Packages

``` coffee
# User
Tern, v0.8.0
file-icons, v1.6.11
highlight-line, v0.11.0
linter, v1.9.1

# Dev
No dev packages
```

**Comment by simmo1210** [comment]
I just got this on a fresh install in Windows 8

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [Tern](https://github.com/artoale/atom-tern) package, v0.8.0

### Stack Trace

Failed to load the Tern package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (C:\Users\simmo\.atom\packages\Tern\lib\tern-view.coffee:1:1)
  at C:\Users\simmo\.atom\packages\Tern\lib\tern-view.coffee:6:5
  at Object.<anonymous> (C:\Users\simmo\.atom\packages\Tern\lib\tern-view.coffee:129:5)
  at Object.<anonymous> (C:\Users\simmo\.atom\packages\Tern\lib\tern-view.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\simmo\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\simmo\.atom\packages\Tern\lib\tern.coffee:1:12)
  at Object.<anonymous> (C:\Users\simmo\.atom\packages\Tern\lib\tern.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\simmo\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\simmo\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:725:34)
  at C:\Users\simmo\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:176:28
  at Package.module.exports.Package.measure (C:\Users\simmo\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:153:15)
  at Package.module.exports.Package.load (C:\Users\simmo\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:167:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\simmo\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package-manager.js:396:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\simmo\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package-manager.js:473:30)
  at C:\Users\simmo\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:444:29
  at exit (C:\Users\simmo\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
  at triggerExitCallback (C:\Users\simmo\AppData\Local\atom\app-1.1.0\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\simmo\AppData\Local\atom\app-1.1.0\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

### Commands

```
```

### Config

``` json
{}
```

### Installed Packages

``` coffee
# User
Tern, v0.8.0

# Dev
No dev packages
```

**Comment by raghavkaul** [comment]
Whoops, looks like this is already reported here https://github.com/artoale/atom-tern/issues/19. Maybe merge the two tickets?

**Comment by cristian-sima** [comment]
Same here

**Comment by sbrl** [comment]
Same here.

Here's my stack trace:

```
TypeError: Cannot read property 'prototype' of undefined
    at __extends (/home/sbrl/.atom/packages/Tern/lib/tern-view.coffee:1:1)
    at /home/sbrl/.atom/packages/Tern/lib/tern-view.coffee:6:5
    at Object.<anonymous> (/home/sbrl/.atom/packages/Tern/lib/tern-view.coffee:6:5)
    at Object.<anonymous> (/home/sbrl/.atom/packages/Tern/lib/tern-view.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/opt/atom/resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```

Here's my uname -a:

```
Linux Snowflake 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

I'm using atom 1.1.0 on Ubuntu 15.10.

**Comment by muzir** [comment]
[Enter steps to reproduce below:]

1.Install tern js form settings package manager
2. Restart Atom 

**Atom Version**: 1.2.1
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [tern](https://github.com/artoale/atom-tern) package, vundefined

### Stack Trace

Failed to load the Tern package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (file:///C:/Users/erhun.baycelik/.atom/packages/tern/lib/tern-view.coffee:1:1)
    at file:///C:/Users/erhun.baycelik/.atom/packages/tern/lib/tern-view.coffee:6:5
    at Object.<anonymous> (file:///C:/Users/erhun.baycelik/.atom/packages/tern/lib/tern-view.coffee:6:5)
    at Object.<anonymous> (file:///C:/Users/erhun.baycelik/.atom/packages/tern/lib/tern-view.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\erhun.baycelik\AppData\Local\atom\app-1.2.1\resources\app.asar\src\compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
Tern, v0.8.0

# Dev
No dev packages
```

**Comment by shanalikhan** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.0-beta3
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [Tern](https://github.com/artoale/atom-tern) package, v0.8.0

### Stack Trace

Failed to load the Tern package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (C:\Users\skhan\.atom\packages\Tern\lib\tern-view.coffee:4:199)
    at C:\Users\skhan\.atom\packages\Tern\lib\tern-view.coffee:9:5
    at Object.<anonymous> (C:\Users\skhan\.atom\packages\Tern\lib\tern-view.coffee:129:5)
    at Object.<anonymous> (C:\Users\skhan\.atom\packages\Tern\lib\tern-view.coffee:131:4)
    at Module._compile (C:\Users\skhan\AppData\Local\atom\app-1.3.0-beta3\resources\app.asar\src\native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\skhan\AppData\Local\atom\app-1.3.0-beta3\resources\app.asar\src\compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\skhan\AppData\Local\atom\app-1.3.0-beta3\resources\app.asar\src\native-compile-cache.js:41:21)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
.bin, vundefined
angularjs-styleguide-snippets, v0.7.3
atom-ternjs, v0.8.4
browser-plus, v0.0.54
emmet, v2.3.14
highlight-selected, v0.11.1
jshint, v1.8.3
linter, v1.11.2
minimap, v4.16.0
minimap-highlight-selected, v4.3.1
project-manager, v2.6.5
seti-syntax, v0.4.1
seti-ui, v0.8.1
sync-settings, v0.6.0
Tern, v0.8.0

# Dev
No dev packages
```

**Comment by shanalikhan** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.0-beta6
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [Tern](https://github.com/artoale/atom-tern) package, v0.8.0

### Stack Trace

Failed to load the Tern package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (C:\Users\skhan\.atom\packages\Tern\lib\tern-view.coffee:4:199)
    at C:\Users\skhan\.atom\packages\Tern\lib\tern-view.coffee:9:5
    at Object.<anonymous> (C:\Users\skhan\.atom\packages\Tern\lib\tern-view.coffee:129:5)
    at Object.<anonymous> (C:\Users\skhan\.atom\packages\Tern\lib\tern-view.coffee:131:4)
    at Module._compile (C:\Users\skhan\AppData\Local\atom\app-1.3.0-beta6\resources\app.asar\src\native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\skhan\AppData\Local\atom\app-1.3.0-beta6\resources\app.asar\src\compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\skhan\AppData\Local\atom\app-1.3.0-beta6\resources\app.asar\src\native-compile-cache.js:41:21)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
.bin, vundefined
angularjs-styleguide-snippets, v0.7.3
atom-ternjs, v0.10.2
browser-plus, v0.0.54
emmet, v2.3.15
highlight-selected, v0.11.1
jshint, v1.8.3
linter, v1.11.3
minimap, v4.16.2
minimap-highlight-selected, v4.3.1
project-manager, v2.6.5
seti-syntax, v0.4.1
seti-ui, v0.8.1
sync-settings, v0.6.0
Tern, v0.8.0

# Dev
No dev packages
```

**Comment by pcambra** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.4.3
**System**: Mac OS X 10.10.5
**Thrown From**: [Tern](https://github.com/artoale/atom-tern) package, v0.8.0

### Stack Trace

Failed to load the Tern package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/pcambra/.atom/packages/tern/lib/tern-view.coffee:1:1)
    at /Users/pcambra/.atom/packages/tern/lib/tern-view.coffee:6:5
    at Object.<anonymous> (/Users/pcambra/.atom/packages/tern/lib/tern-view.coffee:6:5)
    at Object.<anonymous> (/Users/pcambra/.atom/packages/tern/lib/tern-view.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/pcambra/.atom/packages/tern/lib/tern.coffee:1:12)
    at Object.<anonymous> (/Users/pcambra/.atom/packages/tern/lib/tern.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:722:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:443:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:393:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:684:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "audioBeep": false,
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
Tern, v0.8.0
atom-ternjs, v0.13.2
node-debugger, v1.3.2
remote-edit, v1.8.22
space-tab, v0.4.2
tabs-to-spaces, v0.11.1

# Dev
No dev packages
```

**Comment by robophil** [comment]
Same error on ubuntu 14.04 L.T.S

**Comment by nicobevilacqua** [comment]
Same error on ubuntu 14.04 and atom 1.6

**Comment by Hosar** [comment]
Same here, any solution?

**Comment by mliq** [comment]
Same here, OSX 10.11.5

**Comment by andy9775** [comment]
same issue on osx 10.10.5 and atom 1.8.0. I did have tern working for a bit, then adding the `node-express` plugin caused a `cannot read property 'length' of null` issue. I reinstalled the package via apm and now both issues exist.

**Comment by the-simian** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.9.9
**System**: Microsoft Windows 10 Pro
**Thrown From**: [Tern](https://github.com/artoale/atom-tern) package, v0.8.0

### Stack Trace

Failed to load the Tern package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (file:///C:/Users/TotallyRadDueHeyooooo/.atom/packages/tern/lib/tern-view.coffee:1:1)
    at file:///C:/Users/TotallyRadDueHeyooooo/.atom/packages/tern/lib/tern-view.coffee:6:5
    at Object.<anonymous> (file:///C:/Users/TotallyRadDueHeyooooo/.atom/packages/tern/lib/tern-view.coffee:6:5)
    at Object.<anonymous> (file:///C:/Users/TotallyRadDueHeyooooo/.atom/packages/tern/lib/tern-view.coffee:1:1)
    at Module._compile (C:\Users\TotallyRadDueHeyooooo\AppData\Local\atom\app-1.9.9\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Bedroom\AppData\Local\atom\app-1.9.9\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\Bedroom\AppData\Local\atom\app-1.9.9\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Bedroom/.atom/packages/tern/lib/tern.coffee:1:12)
    at Object.<anonymous> (file:///C:/Users/Bedroom/.atom/packages/tern/lib/tern.coffee:1:1)
    at Module._compile (C:\Users\Bedroom\AppData\Local\atom\app-1.9.9\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Bedroom\AppData\Local\atom\app-1.9.9\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\Bedroom\AppData\Local\atom\app-1.9.9\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Bedroom\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package.js:715:27)
    at C:\Users\Bedroom\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (C:\Users\Bedroom\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\Bedroom\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Bedroom\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package-manager.js:457:14)
    at C:\Users\Bedroom\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package-manager.js:402:19
    at Config.module.exports.Config.transact (C:\Users\Bedroom\AppData\Local\atom\app-1.9.9\resources\app.asar\src\config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\Bedroom\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package-manager.js:397:19)
    at C:\Users\Bedroom\AppData\Local\atom\app-1.9.9\resources\app.asar\src\atom-environment.js:749:28
```

### Commands

```
```

### Config

``` json
{
  "core": {}
}
```

### Installed Packages

``` coffee
# User
atom-beautify, v0.29.10 (inactive)
atom-jade, v0.3.0 (inactive)
atom-material-syntax, v0.4.6 (inactive)
atom-material-ui, v1.3.3 (inactive)
atom-ternjs, v0.14.2 (inactive)
language-babel, v2.32.2 (inactive)
linter-markdown, v2.0.1 (inactive)
markdown-preview-plus, v2.4.0 (inactive)
markdown-scroll-sync, v2.1.2 (inactive)
markdown-writer, v2.5.1 (inactive)
minimap, v4.24.7 (inactive)
minimap-cursorline, v0.2.0 (inactive)
minimap-find-and-replace, v4.5.1 (inactive)
minimap-pigments, v0.2.1 (inactive)
Remote-FTP, v0.8.3 (inactive)
Stylus, v3.0.0 (inactive)
Tern, v0.8.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.0 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.0 (inactive)
bookmarks, v0.41.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.39.0 (inactive)
fuzzy-finder, v1.3.0 (inactive)
git-diff, v1.1.0 (inactive)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (inactive)
image-view, v0.58.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (inactive)
metrics, v0.53.1 (inactive)
notifications, v0.64.1 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.67.1 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.1 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (inactive)
timecop, v0.33.1 (inactive)
tree-view, v0.208.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.34.0 (inactive)
whitespace, v0.32.2 (inactive)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.0 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.36.2 (inactive)
language-gfm, v0.86.0 (inactive)
language-git, v0.13.0 (inactive)
language-go, v0.42.0 (inactive)
language-html, v0.44.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.22.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.0 (inactive)
language-less, v0.29.3 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.0 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.68.5 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.52.0 (inactive)
language-shellscript, v0.22.3 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.21.1 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.8 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by dandelionsam** [comment]
Same here:
Os: Ubuntu 17.10
```
TypeError: Cannot read property 'prototype' of undefined
    at extend (/home/simone/.atom/packages/Tern/lib/tern-view.coffee:1:1)
    at /home/simone/.atom/packages/Tern/lib/tern-view.coffee:4:7
    at Object.<anonymous> (/home/simone/.atom/packages/Tern/lib/tern-view.coffee:63:22)
    at Object.<anonymous> (/home/simone/.atom/packages/Tern/lib/tern-view.coffee:1:1)
    at Object.<anonymous> (/home/simone/.atom/packages/Tern/lib/tern-view.coffee:1:1)
    at Module.get_Module._compile (/snap/atom/112/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/snap/atom/112/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///snap/atom/112/usr/share/atom/resources/app.asar/static/index.js:47:45)
    at require (/snap/atom/112/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/simone/.atom/packages/Tern/lib/tern.coffee:1:12)
    at Object.<anonymous> (/home/simone/.atom/packages/Tern/lib/tern.coffee:1:1)
    at Object.<anonymous> (/home/simone/.atom/packages/Tern/lib/tern.coffee:1:1)
    at Module.get_Module._compile (/snap/atom/112/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/snap/atom/112/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///snap/atom/112/usr/share/atom/resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/snap/atom/112/usr/share/atom/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/snap/atom/112/usr/share/atom/resources/app/src/package.js:937:35)
    at /snap/atom/112/usr/share/atom/resources/app/src/package.js:160:34
    at Package.module.exports.Package.measure (/snap/atom/112/usr/share/atom/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/snap/atom/112/usr/share/atom/resources/app/src/package.js:145:18)
    at PackageManager.loadAvailablePackage (/snap/atom/112/usr/share/atom/resources/app/src/package-manager.js:618:16)
    at config.transact (/snap/atom/112/usr/share/atom/resources/app/src/package-manager.js:531:20)
    at Config.module.exports.Config.transact (/snap/atom/112/usr/share/atom/resources/app/src/config.js:342:22)
    at PackageManager.loadPackages (/snap/atom/112/usr/share/atom/resources/app/src/package-manager.js:529:23)
    at /snap/atom/112/usr/share/atom/resources/app/src/atom-environment.js:832:34
```

**Comment by ClarenceIsaboke** [comment]
> Tern crashes upon atom reload after "apm install tern".
> 
> **Atom Version**: 1.1.0
> **System**: "Arch Linux"
> **Thrown From**: [Tern](https://github.com/artoale/atom-tern) package, v0.8.0
> 
> ### Stack Trace
> Failed to load the Tern package
> 
> ```
> At Cannot read property 'prototype' of undefined
> 
> TypeError: Cannot read property 'prototype' of undefined
>     at __extends (/home/user1316/.atom/packages/Tern/lib/tern-view.coffee:1:1)
>     at /home/user1316/.atom/packages/Tern/lib/tern-view.coffee:6:5
>     at Object.<anonymous> (/home/user1316/.atom/packages/Tern/lib/tern-view.coffee:6:5)
>     at Object.<anonymous> (/home/user1316/.atom/packages/Tern/lib/tern-view.coffee:1:1)
>     at Module._compile (module.js:428:26)
>     at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
>     at Module.load (module.js:353:32)
>     at Function.Module._load (module.js:308:12)
>     at Module.require (module.js:363:17)
>     at require (module.js:382:17)
> ```
> 
> ### Commands
> ### Config
> ```json
> {
>   "core": {
>     "projectHome": "~/CODE",
>     "themes": [
>       "one-dark-ui",
>       "solarized-dark-syntax"
>     ],
>     "autoHideMenuBar": true
>   }
> }
> ```
> 
> ### Installed Packages
> ```coffee
> # User
> Tern, v0.8.0
> file-icons, v1.6.11
> highlight-line, v0.11.0
> linter, v1.9.1
> 
> # Dev
> No dev packages
> ```
