### ISSUE TITLE
Cannot find Tern module

### ISSUE THREAD

**Issue by OliverJAsh** [artoale/atom-tern#3]
This appears in my console when I try to use this package:

```
Error: Cannot find module '/Users/Oliver/.atom/packages/Tern/node_modules/.bin/tern'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:279:25)
    at Function.Module.runMain (module.js:496:10)
    at startup (node.js:129:16)
    at node.js:1037:3
```

Do I need to give the package permission to install Tern? I am using a Node version manager if that helps.

**Comment by artoale** [comment]
Should be fixed by v0.3
