### ISSUE TITLE
Server does not start

### ISSUE THREAD

**Issue by despairblue** [artoale/atom-tern#7]
```
Failed to activate package named 'Tern' ReferenceError: editor is not defined
  at Object.<anonymous> (/home/despairblue/.atom/packages/Tern/lib/tern.coffee:8:13)
  at Object.<anonymous> (/home/despairblue/.atom/packages/Tern/lib/tern.coffee:1:1)
  at Module._compile (module.js:455:26)
  at Object.requireCoffeeScript [as .coffee] (/usr/share/atom/resources/app/src/coffee-cache.js:54:19)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:363:17)
  at require (module.js:379:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:485:34)
  at Package.module.exports.Package.activateConfig (/usr/share/atom/resources/app/src/package.js:178:12)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:160:14)
  at Package.module.exports.Package.handleActivationEvent (/usr/share/atom/resources/app/src/package.js:548:12)
  at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app/src/package.js:3:61)
  at HTMLDivElement.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLDivElement.elemData.handle (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4360:28)
  at Object.jQuery.event.trigger (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4594:12)
  at HTMLInputElement.<anonymous> (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:5119:17)
  at Function.jQuery.extend.each (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:590:23)
  at [object Object].jQuery.fn.jQuery.each (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:237:17)
  at [object Object].jQuery.fn.extend.trigger (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:5118:15)
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app/node_modules/command-palette/lib/command-palette-view.js:110:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app/src/select-list-view.js:269:21)
  at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app/src/select-list-view.js:108:24)
  at HTMLDivElement.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLDivElement.elemData.handle (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4360:28)
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:395:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:176:22)
  at HTMLDocument.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:90:29)
  at HTMLDocument.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLDocument.elemData.handle (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4360:28)
 /usr/share/atom/resources/app/src/package.js:168
Error activating package config for “Tern” ReferenceError {} /usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:433
```

**Comment by artoale** [comment]
Uhm - that's weird at best...which version of Atom (and OS) are you using?

**Comment by despairblue** [comment]
Atom: 0.107.0
ArchLinux
tern: 0.6.2

**Comment by artoale** [comment]
Thanks for reporting - I've never actually tested on linux, I'll have a look around :)

**Comment by despairblue** [comment]
Thanks :)

Just updated to 0.112.0 and the error stays the same. So it wasn't the outdated version of atom i had (feels like there's a new release everyday...).

**Comment by cocodrino** [comment]
open  your tern.coffee (/home/despairblue/.atom/packages/Tern/lib/tern.coffee) and in the line 8 add a parenthesis around editor...this would fix the problem...

```
    update: (editor) ->
```

**Comment by despairblue** [comment]
Thanks, that does fix it actually.

**Comment by lmartins** [comment]
This also happen on the mac version.
